image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - cmd: dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1