image: Visual Studio 2019

branches:
  except:
    - gh-pages

environment:
  SonarKey:
    secure: u3sH5Rwmc8zeqtB33llZiMi5bSrB1wy7xlTk4px5OMnRu0WEDzpsDe0y14e0un18
  NuGetKey:
    secure: 2DxptPlvqZ5bmcUo9o9wqBYDk8MiaJ6jG6EjI9woOq0W6XsRYgfRZnxsp3OjOUtz
  COVERALLS_REPO_TOKEN:
    secure: pmewtxEuv8kMwIMIpzrxUgLtEK8DEf90Iu96AiDjXwMObZAaI7ZTByXRZRp5dYYJ

init:
  - ps: dotnet tool install --global dotnet-sonarscanner

build_script:
  - ps: .\build.ps1 appveyor

test: off
deploy: off
