image: Visual Studio 2019 Preview
skip_tags: true

branches:
  except:
    - gh-pages

environment:
  SonarKey:
    secure: u3sH5Rwmc8zeqtB33llZiMi5bSrB1wy7xlTk4px5OMnRu0WEDzpsDe0y14e0un18
  NuGetKey:
    secure: f/oEZedvaPFnnyih3qfwV0G1p9mKfZNpla+8/tkjmOzhKAuFsb+56DurMR2vxW3n

build_script:
  - ps: .\build.ps1 sonar

artifacts:
  - path: 'src\**\*.nupkg'

deploy:
  - provider: GitHub
    release: Ubiety.Dns.Core-v$(appveyor_build_version)
    description: Ubiety DNS for .NET Standard
    auth_token:
      secure: +fxguAe7QHo5zfhN7YRoOqMf4x8ZG4mR29Q8HMY0Y9d4gvwv+NP5daWbQyc0R/BJ
    artifact: /.*\.nupkg/
    draft: true
    prerelease: false
    on:
      branch: master

  - provider: GitHub
    release: Ubiety.Dns.Core.beta-v$(appveyor_build_version)
    description: Ubiety DNS Beta
    auth_token:
      secure: +fxguAe7QHo5zfhN7YRoOqMf4x8ZG4mR29Q8HMY0Y9d4gvwv+NP5daWbQyc0R/BJ
    artifact: /.*\.nupkg/
    draft: true
    prerelease: true