image: Visual Studio 2017
skip_tags: true

branches:
  only:
    - master
    - develop
  except:
    - gh-pages

install:
  - choco install gitversion.portable -pre -y

before_build:
  - cmd: dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build_script:
  - cmd: PowerShell -Version 2.0 .\build.ps1

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: GitHub
    release: Ubiety.Dns.Core-v$(appveyor_build_version)
    description: Ubiety DNS for .NET Standard
    auth_token:
      secure: +fxguAe7QHo5zfhN7YRoOqMf4x8ZG4mR29Q8HMY0Y9d4gvwv+NP5daWbQyc0R/BJ
    artifact: /.*\.nupkg/
    draft: true
    prerelease: false
    on:
      branch: master

  - provider: GitHub
    release: Ubiety.Dns.Core.beta-v$(appveyor_build_version)
    description: Ubiety DNS Beta
    auth_token:
      secure: +fxguAe7QHo5zfhN7YRoOqMf4x8ZG4mR29Q8HMY0Y9d4gvwv+NP5daWbQyc0R/BJ
    artifact: /.*\.nupkg/
    draft: true
    prerelease: true
    on:
      branch: develop