image: Visual Studio 2017

branches:
  except:
    - gh-pages

environment:
  SonarKey:
    secure: u3sH5Rwmc8zeqtB33llZiMi5bSrB1wy7xlTk4px5OMnRu0WEDzpsDe0y14e0un18
  NuGetKey:
    secure: f/oEZedvaPFnnyih3qfwV0G1p9mKfZNpla+8/tkjmOzhKAuFsb+56DurMR2vxW3n

init:
  - ps: dotnet tool install --global dotnet-sonarscanner

build_script:
  - ps: .\build.ps1 sonar

test: off
deploy: off