image: Visual Studio 2017

install:
  - choco install gitversion.portable -pre -y

before_build:
  - cmd: dotnet restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  verbosity: minimal